lesstif/php-jira-rest-client

- src/Issue/Issue.php
- src/Issue/IssueField.php
- src/Issue/IssueService.php
- src/Issue/TimeTracking.php
- src/JiraClient.php
due to incorrect dockblock JsonMapper set stdObject instead of the declare entities.
> fixed incorrect json mapping && add timetracking entity

- README.md
- src/Issue/IssueField.php
- src/Issue/IssueService.php
- src/Issue/TimeTracking.php
- tests/TimeTrackingTest.php
When getting and issue from Jira, I get this exception:
`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class '\JiraRestApi\Issue\Timetracking' not found' in /home/www-prod/debugit/lib/vendor/netresearch/jsonmapper/src/JsonMapper.php:206`
It tries to instantiate a Time**t**racking class instead of Time**T**racking class. This seems to be since we receive from JIRA the field `timetracking` and then the JsonMapper tries to map it to an Object instance with by uppercasing the first letter of the field.
This is only a problem on unix machines, not on Windows.
Renaming the Class to `Timetracker` does the trick
> Changed TimeTracking to Timetracking since it breaks when generating class with JsonMapper on Unix machines

- src/JiraClient.php
Don't know why it was here. Maybe an error during merging ?
> Delete unexpected ":end"

- README.md
- src/Issue/IssueField.php
- src/Issue/IssueService.php
@lesstif Thanks for creating this library! A couple things I wanted to update:
- Using the bulk insert endpoint for uploading large batches of issues
- Why: Faster, and bulk insert seems to be more forgiving in that it uploads issues that are valid without throwing errors during execution
- I'm not sure if the code fits exactly with your conventions, so let me know if you can integrate this but need some additional changes.
- Allowing assignee to be null
- Why: I was getting an error while using the search function to find issues that did not have an assignee. Assignee isn't required on Jira so it seems like it shouldn't be necessary here.
> Add bulk issue insert and allow assignee to be null

- composer.json
I want to continue to use this package when switching to Laravel 5.3. However:
`laravel/framework v5.3.3 requires symfony/var-dumper 3.1.* `
Hence this pull request.
Also, shouldn't it be in require-dev?  I don't see any reason var-dumper has any use in a production environment (unsure what it's used for though)
Thanks
> Improved version constraints

- composer.json
- src/Issue/IssueField.php
- src/Issue/IssueService.php
- src/JiraClient.php
- src/User/UserService.php
Added search to the UserService.  Took a stab at allowing custom fields, by allowing the user to pass an instantiated object that extends from the Issue and overrides the fields object.  Allow passing in an external logger to the client.
Example custom issue and fields:
use JiraRestApi\Issue\Issue;
class JiraIssue extends Issue
{
/**
* @var JiraIssueField
*/
public $fields;
}
use JiraRestApi\Issue\IssueField;
class JiraIssueField extends IssueField
{
/** @var  string|null */
public $customfield_10018;
/** @var  string|null */
public $customfield_10016;
}
> User Search, Custom IssueFields, External Logger

- .gitignore
- src/Project/ProjectService.php
- src/Project/ProjectType.php
- tests/ProjectTest.php
Hi @lesstif,
here the squashed Version.
Alex
> Added ProjectType

- src/Issue/IssueService.php
Add is_array check in \JiraRestApi\Issue\IssueService::addAttachments method.
Sometimes I'm getting an error from netresearch/jsonmapper/src/JsonMapper.php:350 with message 'Invalid argument supplied for foreach()'
> Add is_array check in IssueService::addAttachments

- README.md
- src/Issue/IssueService.php
- tests/IssueTest.php
add availability to define query parameters to delete issues with sub-tasks or update issues without send notifications in example
> Added tests from #56

- src/Issue/Comment.php
When setting a comment visibility and pushing to Jira, the visibility data is being removed because its missing the jsonSerialize() interface.
> Comment Visibility Not Serializing

- src/JiraClient.php
- Fix "\JiraRestApi\JsonMapperHelper::class" syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' on PHP 5
- Fix for curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
> Fixed bugs

- src/JiraClient.php
Fix for another curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true); cannot be activated when an open_basedir is set
> Fix for another curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true); 

- src/Group/GroupService.php
Fixes
Class 'JiraRestApi\Group\User' not found in lesstif/php-jira-rest-client/src/Group/GroupService.php:30
> Map Group objects on group->get() method

- src/JiraClient.php
By adding this small and simple functionality, the library will be able to make requests to '/rest/agile/1.0' for example, enabling it to get boards, get sprints and such.
> Added custom Jira API URI setter to JiraClient

- src/Issue/IssueService.php
- src/Issue/Watcher.php
Would like to add function to get all issue watchers
[Documentation page](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-watchers-get)
> Add function to get issue watchers

- src/Project/ProjectService.php
Before this commit, getAllProjects doesn't return some project properties [(reference)](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-project-get). So if you need the description you have to use the getProject function for every project.
Now, with this change you can use the expand query parameter to ask for the following information:
*    description - description of the project.
*   projectKeys - all project keys associated with the project.
*    lead - project lead. Note, that project lead role is different from project administrator one.
*    issueTypes - issue types associated with the project.
*    url - a URL associated with the project.
The following code is an example of use:
``$this->getProjectService()->getAllProjects(['expand'=>['description']]);``
> Support expand attribute in GetAllProjects

- src/Issue/IssueField.php
In some situations the reporter can be null but a JSON mapping exception is thrown when it does.
> Fix issue when reporter is null

- src/Issue/Attachment.php
- src/Issue/ChangeLog.php
- src/Issue/Comment.php
- src/Issue/Comments.php
- src/Issue/History.php
- src/Issue/Issue.php
- src/Issue/IssueField.php
- src/Issue/IssueSearchResult.php
- src/Issue/IssueStatus.php
- src/Issue/IssueType.php
- src/Issue/RemoteIssueLink.php
- src/Issue/Transition.php
Hello,
First of all, thank you for this package. We use it at work, but we have run into a problem that this PR will fix.
In our project we use 2 loaders, 1 is the composer's autoloader and the other one is the yii 1.1 framework's autoloader. Now the issue is that when jsonmapper, tries to instantiate a class from the json response, looks at the docblocks for a class with the name e.g ChangeLog, but it can not find the class using the composer's autoloader. Then (in our project only) is the turn of the yii autoloader to look for the class, which is also unable to locate it and an exception is thrown.
In most projects this wont be an issue because they will use only the composer's autoloader which will fail the first time to locate the class but it will locate it in another pass it will …
> Use full namespaces in doc blocks, for the json mapper.

- composer.json
- src/Configuration/AbstractConfiguration.php
- src/Configuration/ArrayConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/JiraClient.php
Hi,
For some unknown reason all requests return status code 200 but empty body (Jira v7.8.2).
The problem was that request doesn't contain curl user-agent.
I didn't find easy way to make all curl options configurable, so I just add this parameter to configs.
Off-topic: Is there any reason folder "php-jira-rest-client/src/**sprint**/" to be lower case?
> Add configurable CURLOPT_USERAGENT

- src/Sprint/SprintService.php
This is a fix for Attempt to Pull by Sprint ID calls incorrect endpoint #190, 
Instead of getSprint method requiring SprintObject updated getSprint method of SprintService to need a sprintID, so sprint works like other get methods, like getProject in ProjectService.
> Fixed SprintService so sprint can be pulled by ID.

- src/JiraClient.php
add `CURLOPT_ENCODING` to curl.
see http://php.net/curl_setopt
```
The contents of the "Accept-Encoding: " header. This enables decoding of the response.
Supported encodings are "identity", "deflate", and "gzip".
If an empty string, "", is set, a header containing all supported encoding types is sent. 
```
> add curl compression

- README.md
Latest Atlassian JIRA Server API version is `7.12.2`.
Using `latest` as api version, api automatically redirecting to latest version in the documentation.
> README.md: Updated Atlassian API links from 7.6.1 version to the latest

- composer.json
- src/Issue/Attachment.php
- src/Issue/Comment.php
- src/Issue/IssueField.php
- src/Issue/Version.php
- src/Issue/Worklog.php
- src/JiraClient.php
- src/Version/VersionService.php
- tests/AssigneeTest.php
- tests/MapperTest.php
This is the PR for #211. After merging it, `\DateTimeImmutable` can be supplied as input in all places where only `\DateTime` was supported before.
Example:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$wl = new \JiraRestApi\Issue\Worklog();
$wl->setStartedDateTime(new DateTimeImmutable());
var_dump($wl);
```
It's using JsonMapper's `classMap` feature to tell it that instead of trying to create `\DateTimeInterface` objects (which won't work, since it's an interface), it should create `\DateTime` objects instead. This also means that when JIRA Rest Client instantiates an object from a string, it will use `\DateTime` as before and therefore not break existing code using this library.
This PR currently includes a workaround for a quirk in JsonMapper, cweiske/jsonmapper#111. …
> Use DateTimeInterface instead of DateTime

- src/JiraClient.php
In download() and upload() method the curl configuration did not use the proxy settinge available from ConfigurationInterface. This is added by this commit.
> Use Proxy Configuration for curl handle

- src/JiraClient.php
The current code calls curl_init and curl_close before and after each request.  if you make a lot of requests to the same server this is very costly over https.  If you don't destory the curl resource curl will use http keepalive.  This change gave me about a 4x speed up against my production instance for changing one custom field on a lot of tickets.
> Persist curl resource between requests

- src/Board/BoardService.php
Added a method to retrieve all board sprints.
Didn't add tests, since some of the board are hardcoded in your Jira instance so there's no good way for me to test this, except using on my own code, which I'm doing
> Add capability to retrieve all board sprints

- src/Version/VersionService.php
Fixes https://github.com/lesstif/php-jira-rest-client/issues/259
There is no case where the jira version request returns an array as far as i know.
> return version instead of array of unknown project type

- src/Issue/IssueField.php
When chaining method calls `setParentKeyOrId()` returns `null` and therefore breaks the chain.
> Return $this when calling setParentKeyOrId()

- src/Issue/IssueService.php
When requesting transitions, if you want to apply a transition you might need to query the fields it has, which are not included when you do the request without additional parameters. 
With this change, we can get them like this:
`$issueService->getTransition("ISS-001", 
["expand" => "transitions.fields"]
);`
> add optional paramArray parameter to IssueService getTransition

- src/Issue/IssueField.php
Jira's API is deprecating functionalities that tamper with usernames and will only allow the use of accountId. This includes the creation of new issues and changing/setting the reporter by name.
This allows to set the reporter's accountId, which can circumvent this problem.
> setReporterAccountId (conforms to new API rules)

- README.md
Two example codes in the README that I came across had the wrong error message.
> Update example code error messages

- src/Issue/IssueService.php
- tests/WorkLogTest.php
Hi!
First of all, Thank you for great project!
I needed to remove Jira ticket Worklog and I didn't found option to this in current code.
This PR introduces new public deleteWorkflow method right next to editWorklog and addWorklog.
I was not able to figure out how to write test case. I assume I need to fire up local jira service that I'm not willing to do. Please adjust my test case if it fails.. I do not have a way to properly prepare it locally.
> added deleteWorkflow method to JiraRestApi\Issue\IssueService

- .travis.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
Closes #311 
:yum: Implements phpstan coverage by travis build.
Added `phpstan-baseline.neon` because of errors on analyse `level: 0`.
**Test without baseline**
**Test with baseline**
> implement phpstan for travis build

- src/Project/Project.php
This pull request will add the leadAccountId to the project model. We cannot use the lead parameter when creating a new project via the API due to the GDPR- strict mode of our Jira cloud installation / the deprecation of the usage of usernames in favor of accountIds:
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/
> Support leadAccountId parameter

- src/Issue/IssueService.php
- src/Request/Author.php
- src/Request/RequestComment.php
- src/Request/RequestService.php
- src/ServiceDeskTrait.php
For a project we are working on, we need to be able to make private comments on service desk requests via the API. This adds that capability.
Tested with Jira 8.9.1 and Service Desk 4.9.1
> Add service desk public and private comments on requests

- composer.json
- src/Attachment/AttachmentService.php
- src/Auth/AuthService.php
- src/Board/BoardService.php
- src/Component/ComponentService.php
- src/Epic/EpicService.php
- src/Field/FieldService.php
- src/Group/GroupService.php
- src/Issue/AgileIssueService.php
- src/Issue/IssueService.php
- src/JiraClient.php
- src/Priority/PriorityService.php
- src/Project/ProjectService.php
- src/RapidCharts/ScopeChangeBurnDownChartService.php
- src/Request/RequestService.php
- src/Sprint/SprintService.php
- src/Status/StatusService.php
- src/User/UserService.php
- src/Version/VersionService.php
- tests/BoardTest.php
> WIP remove $configuration, and clean up exec, upload and download

- src/JiraClient.php
- src/JiraException.php
Hi,
this PR adds storing of Jira response into JiraException in case of failed request. You can than easily read it in catch block and display errors to user.
Currently it is possible to retrieve response only from exception message using regexp which is more like a workaround.
Example of usage:
```php
try {
// some operation which throws JiraException
} catch (\JiraRestApi\JiraException $e) {
$response = $e->getResponse();
if ($response) {
// request finished with status code >= 400
$response = json_decode($response);
$jiraErrorMessages = $response->errorMessages;
$jiraErrors = $response->errors;
} else {
// request failed without response (possibly network error)
}
}
```
> Store Jira error response into JiraException

- src/Issue/IssueField.php
Hi,
this PR modifies mapping to absolute namespace for `$reporter` property. I extend `IssueField` class in my project and JsonMapper tries to find `Reporter` class in my own application namespace. This also unifies mapping with other properties which all uses absolute namespace `\JiraRestApi\Issue\<className>`.
Thanks!
> Use absolute namespace for Reporter

- phpstan.neon.dist
Not sure why these files were included here, they do not seem to be needed and PHPStan did not run because they don't exist.
Now `vendor/bin/phpstan analyze` works fine, as you can see in Travis.
> Fix PHPStan

- phpstan-baseline.neon
- phpstan.neon.dist
- src/Configuration/DotEnvConfiguration.php
- src/Issue/JqlQuery.php
- src/Issue/VisibilityTrait.php
- src/IssueType/IssueTypeService.php
- src/JiraClient.php
- src/Project/Project.php
- src/StatusCategory/StatusCategoryService.php
Fixed PHPStan errors, now it is green :tada: 
Also increased level to 5, it mostly added some basic PHPDoc mistakes. 
Also there were errors that things [like this](https://github.com/lesstif/php-jira-rest-client/blob/1ca81b97a82e4ae1b3ff0821aa6afc89f2f60219/src/Issue/Transition.php#L33) are always false. It seems like it could make sense to either add `|null` in PHPDoc or initialize in the field definition. But I guess it may affect JSON mapping (at least the first approach), so I disabled these errors for now.
> Fix PHPStan errors

- src/Configuration/AbstractConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/JiraClient.php
In some cases when Jira is not available it can be useful to specify a timeout to prevent the application from freezing.
P.S.
there is a suggestion to add the ability of adding custom CURL options for next request via method in JiraClient class, what do you think about it?
> jira_client_optional_curl_opts | added CURLOPT_CONNECTTIMEOUT

- src/Issue/IssueService.php
Allow parameters to be passed to getWorklog so we can filter by startedAfter etc
> Update getWorklog to accept parameters.

- src/Configuration/DotEnvConfiguration.php
I'm still running into the issue outlined in #352 witht he most recent code. 
In my case I'm running getAllProjects() from within a scheduled Laravel job. This fails due to $_ENV not being sufficient to read this variables. 
A simple workaround for me was to fallback to the existing env() method, but I am aware that this might not be the best approach as it is not framework agnostic, but I still wanted to put this workaround out there as it may help others.
> related to #352 - environment variables cannot be always read 

- src/JiraClient.php
Fixes problem in PHP 8.1:
```
Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in vendor/lesstif/php-jira-rest-client/src/JiraClient.php on line 515
```
> Argument to file_exists() must be string

- src/Configuration/DotEnvConfiguration.php
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in lesstif/php-jira-rest-client/src/Configuration/DotEnvConfiguration.php on line 67
#untested
> Catch passing null to strtolower

- src/Issue/IssueField.php
Solves a situation where you would get an error if you would update a custom field of type 'Number field'. 
Error Message: 
```{"errorMessages":[],"errors":{"customfield_11152":"Specify a number for the custom field (below 100,000,000,000,000)"}}```
Reproduce: 
```
$issueKey = 'PRO-123';
$number = 50;
$numberField = new IssueField(true);
$numberField->addCustomField('customfield_11152', $number);
$editParams = [
'notifyUsers' => false,
];
$ret = $this->issueService->update($issueKey, $numberField, $editParams);
```
_Make sure `customfield_11152` is of type 'Number field'_
> Change type declaration of IssueField::addCustomField to allow integer and float values

- src/Issue/AgileIssueService.php
`AgileApiTrait` is missing from the package, to fix the `AgileIssueService` from breaking I have replaced the method called from `AgileApiTrait` with the `setApiUri` function.
> Replaced missing AgileApiTrait with setApiUri function

- src/Issue/ContentField.php
I don't know why, but without the version it doesn't work for me.
And in PHP 8.2 I get a warning, that I should not create dynamic properties :-)
> Add version to ContentField

- src/Issue/Comments.php
PHP Deprecated:  Creation of dynamic property JiraRestApi\Issue\Comments::$self is deprecated in /vendor/lesstif/php-jira-rest-client/src/JsonMapperHelper.php on line 25
> Add self to Comments

- src/Issue/IssueType.php
- src/Issue/Reporter.php
- src/Issue/Transition.php
- src/Project/Project.php
This PR tackles further deprecation warnings that are thrown under PHP 8.2 for relying on dynamic property creation.
> Tackle further PHP 8.2 deprecation warnings.

- src/Issue/IssueStatus.php
Issue status description is nullable in JIra. 
This has been fixed in the Status::class (see pr: https://github.com/lesstif/php-jira-rest-client/pull/477) however has not been fixed in the IssueStatus ::class.
> Refactored IssueStatus $description to accept null

- src/Configuration/AbstractConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/JiraClient.php
Allows the use of other cURL proxy types besides CURLPROXY_HTTP, e.g. CURLPROXY_SOCKS5.
> Add cURL proxy type configuration

- src/Issue/IssueField.php
e.g. to remove a previous selection from a checkbox field, see #525
> Allow null values in addCustomField

- composer.json
- src/JiraClient.php
Currently the Jira timeout settings are not set in `JiraClient::exec()`. So the requests can take very long. Since the default is set to 30 seconds. In my case I am injecting this configuration values to `\JiraRestApi\Configuration\ArrayConfiguration::__construct()`. This PR improves this.
> Introduce timeout to cURL exec from .env file

- src/ServiceDesk/Request/RequestService.php
- tests/ServiceDesk/Request/RequestServiceTest.php
Accessing [endpoint](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-worklogs/#api-rest-api-2-worklog-list-post) to find worklog location using just its id.
> feat: added endpoint to find workload by ID

- README.md
- src/Board/BoardResult.php
- src/Board/BoardService.php
- src/Board/PaginatedResult.php
- tests/BoardTest.php
The current implementation of the `BoardService->getBoardList()` method will only return the first 50 results from the Jira Board endpoint (`/rest/agile/1.0/board`). 
Rather than modify the existing `getBoardList()` method and introduce a breaking change, I created a new method -- `getBoards()` -- which maps the response data from `/rest/agile/1.0/board` into a newly created BoardResult object.  This new object has properties for data like total results, and a `isLast` boolean, which are returned by the endpoint but currently ignored by `getBoardList()`. 
Using this new object data, developers can easily make multiple calls to the `/rest/agile/1.0/board` endpoint to retrieve the entire list of boards rather than just the first 50. 
I added this information to the ReadMe and added an …
> Add New Method for Returning Board List With Offset/Paginated Results

- src/Component/Component.php
- src/Issue/Issue.php
- src/Issue/IssueField.php
- src/Issue/IssueType.php
- src/Issue/Reporter.php
- src/Project/Project.php
- src/ServiceDesk/Customer/Customer.php
This PR is similar to #543, but sets the default values for all nullable properties.
This fixes php errors in the form of:
```
Typed property JiraRestApi\Issue\IssueField::$resolution must not be accessed before initialization
```
> Set default to null for all nullable properties

- src/Issue/Comment.php
On PHP >=  8.2 allow comment to have renderedBody property correctly set upon deserialization.
> On PHP >=  8.2 allow comment to have renderedBody property correctly set upon deserialization.

- src/JiraClient.php
Since the version 5 of the JsonMapper the property bStrictObjectTypeChecking is true by default. This causes error when JsonMapper maps string dates to DateTimeInterface.
This fix sets the property to false.
>  disable strict object type check in JsonMapper

- src/Issue/Issue.php
- src/Issue/IssueField.php
`Changelog` and `fixVersions` are not initialized if the fields are empty in Jira.
This causes `Typed property must not be accessed before initialization` errors on our side.
> Set default values for changelog + fixVersions

- src/Issue/IssueSearchResult.php
It seems Jira was updated. 
Jira now returns the `expand` property with a null value. 
Appearently, the JsonMapper takes issue with this, resulting in this error:
`Fix ["JSON property \"expand\" in class \"JiraRestApi\\Issue\\IssueSearchResult\" must not be NULL"]`
This change makes the `expand` field accept null values.
> Fix: `expand` property in IssueSearchResult not nullable

- src/Issue/IssueBulkResult.php
- src/Issue/IssueService.php
> fix deprecated search to search/jql
