- src/Issue/IssueField.php
- src/Project/ProjectService.php
- IssueField class - Added missing IssueType functions
- ProjectService class - second parameter changed to false to fix mapArray
> IssueField and ProjectService fix

- src/Configuration/AbstractConfiguration.php
- src/Configuration/ArrayConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/Issue/IssueField.php
- src/Issue/IssueService.php
- src/JiraClient.php
- src/Project/ProjectService.php
now we can write framework modules
> external configuration, framework compability

- src/Issue/IssueField.php
Here are two bug fixes regarding comments and issue types.
> Fix missing comments due to a misnamed key.

- src/User/User.php
- src/User/UserService.php
currently only get user function added
> support for user service added

- src/Issue/IssueField.php
Fixed browsing completed tasks with null priority
> bugfix-priority

- composer.json
My app need a newest version of netresearch/jsonmapper
> Update version of netresearch/jsonmapper

- README.md
- src/Issue/IssueService.php
- src/Issue/Watcher.php
- tests/WatcherLogTest.php
(cherry picked from commit 9d5d29f)
> implement addWatcher method

- src/Issue/Version.php
> Fix searching issues with fixVersion

- src/Issue/IssueService.php
Based on the createmeta method I'd like to add a new function to retrieve issues metadata
https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-getCreateIssueMeta
> Add function to call createmeta method

- src/JiraClient.php
Created a function to close the curl handles instead of having a goto :)
> Cleaning goto from JiraClient.php

- src/User/User.php
- src/User/UserService.php
Would like to add a possibility to create new users. 
[Official documentation](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-user-post)
> Added function to create a new user

- README.md
- src/Group/GroupService.php
- src/Issue/IssueField.php
- src/User/UserService.php
add links to jira api reference to readme, near examples.
improve docs in readme, add JqlFunction, add note to transitions.
fix some warnings and errors in examples in readme.
fix some warnings in methods phpdoc and code
> update docs & fix some warnings

- src/Issue/IssueField.php
on 1.19.1 broken partial update
by https://github.com/lesstif/php-jira-rest-client/issues/126
> fix Call to a member function isEmpty() on null

- src/Issue/IssueField.php
Fixes https://github.com/lesstif/php-jira-rest-client/issues/131
> Do not set default on IssueField::$versions

- src/Priority/Priority.php
- src/Priority/PriorityService.php
Fix #154 
This PR allows to get all priorities defined on Jira as it can be configured on every single install.
> Create priorities Service.

- src/Issue/CustomFieldUsage.php
- src/Issue/VersionIssueCounts.php
- src/Version/VersionService.php
This implements the getRelatedIssues function in the VersionService.
> Implement functionality for getRelatedIssues in VersionService

- src/Issue/VersionUnresolvedCount.php
- src/Version/VersionService.php
Adds getUnresolvedIssues to the VersionService.  The naming of this function aligns with Jira, even though it only returns a count.
> Add getUnresolvedIssues to VersionService

- src/Issue/IssueService.php
Add functionality to alter the fixVersions on an issue using the same logic as updateLabels
> Add functionality to alter the fixVersions on an issue

- README.md
- composer.json
Laravel support auto-discover packages from `5.5` version (latest is `5.7`).
See: https://laravel.com/docs/5.7/packages#package-discovery
> Added Laravel auto-discover support

- src/Auth/AuthService.php
- src/Issue/IssueService.php
- src/Issue/JqlQuery.php
- src/Version/VersionService.php
#207 has been updated links in the README.md file, #209 updating links in the phpDocs blocks of classes.
> Update Atlassian API links from 7.6.1 version to the latest in phpDocs

- README.md
- src/Issue/IssueService.php
- tests/WatcherLogTest.php
Just a quick addition to include removeWatcher
> added removeWatcher to issue service

- .env.example
- src/Configuration/AbstractConfiguration.php
- src/Configuration/ArrayConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/JiraClient.php
- src/NoOperationMonologHandler.php
> fixed Pr/239

- src/Sprint/SprintService.php
Added a method to retrieve all sprints issues
Didn't add tests for the same reason as #247
> Add capability to retrieve all sprint issues

- README.md
- src/Issue/Worklog.php
> Support Worklogs for Jira REST API v3. Fixes #254

- src/Component/ComponentService.php
Adds a new service to handle components.
Re-uses the class `\JiraRestApi\Project\Component`.
Maybe it is better to move the class into new namespace `\JiraRestApi\Project`.
> Add service to handle components

- README.md
Related with the changes requested in #228
> Add documentation for board services

- README.md
- src/User/UserService.php
This methods is useful if you want find users by any query. Reference: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-user-search-query-get
> Add method that allow find users by query.

- src/User/UserService.php
Added the getUsers call for v3 (https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-users-search-get)
> Added getUsers call

- README.md
- src/AgileApiTrait.php
- src/Board/BoardService.php
- src/Epic/Epic.php
- src/Epic/EpicColor.php
- src/Epic/EpicService.php
- src/JsonSerializableTrait.php
> Add ability to get Epics on Board and Issues from Epic

- src/Issue/IssueService.php
Summary:
Added remove monitor by account id
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/
> Added remove watcher by accountId

- src/Issue/IssueService.php
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/
> fix: Change parameter to assigneeId on function changeAssignee

- src/Issue/IssueService.php
Reverts lesstif/php-jira-rest-client#291
> Revert "fix: Change parameter to assigneeId on function changeAssignee"

- src/JiraClient.php
> FIX: support multiple attachments

- phpstan-baseline.neon
- src/JiraClient.php
Here we go: delete one error listed in phpstan baseline 😃
> Fix phpstan error: "undefined property JiraRestApi\JiraClient::$cookieFile"

- README.md
Refs https://github.com/lesstif/php-jira-rest-client/issues/327
> Update installation instructions to 2.x versions

- src/Issue/CommentV3.php
when trying to add a "regular" comment when working with API V3 the action fails 
i added CommentV3 class so you can add comments with API V3
> added support for comment in API V3

- src/Configuration/AbstractConfiguration.php
- src/Configuration/ArrayConfiguration.php
- src/Configuration/ConfigurationInterface.php
- src/Configuration/DotEnvConfiguration.php
- src/JiraClient.php
I extended your awesome library to support client certificates to access a jira instance.
would love to see this merged :)
> Feature: Add personal certificate support to connect to jira

- composer.json
This update allows the code to continue to work with Laravel 6
> Update phpdotenv to work with Laravel 6

- src/Issue/IssueService.php
allows static analysis to report errors for the parameters
> more precise phpdocs in IssueService

- src/Issue/JqlFunction.php
- fixes phpdoc
- Better IDE/Tool support on call-sites
- More readable code
> Use variadic parameter

- src/Project/Project.php
> change type of project lead from array to string

- src/Project/Project.php
Reverts lesstif/php-jira-rest-client#422
> Revert "change type of project lead from array to string"

- src/Issue/IssueService.php
closes https://github.com/lesstif/php-jira-rest-client/issues/420
> IssueService: fix php warning regaring invalid argument for foreach

- src/Issue/IssueService.php
This PR fixes #305, just updated it with the latest version.
> Fixed `IssueService::getComments()` method not mapping to the correct object (Comments)

- src/JsonMapperHelper.php
Fixing bug with deleting custom field if it is equal to 0
> Fixing bug when custom field equal to 0

- src/ServiceDesk/Attachment/AttachmentService.php
- src/ServiceDesk/Customer/Customer.php
- src/ServiceDesk/Request/Request.php
- src/ServiceDesk/Request/RequestService.php
- tests/ServiceDesk/Attachment/AttachmentServiceTest.php
- tests/ServiceDesk/Customer/CustomerTest.php
- tests/ServiceDesk/Request/RequestServiceTest.php
Run into a few issues while using the latest version of the ServiceDesk integration
> Fix service desk issues

- README.md
Escaped unescaped ' in strings
> Fix readme code samples (escape ' character)

- composer.json
> Make vlucas/phpdotenv an optional dependency

- src/Sprint/Sprint.php
See https://docs.atlassian.com/jira-software/REST/9.5.0/#agile/1.0/board/{boardId}/sprint
> Add field activatedDate to Sprint

- src/Issue/IssueField.php
In accordance with this problem https://github.com/lesstif/php-jira-rest-client/issues/515, I added a small fix that will solve it
> add fix for nullable parent prop in IssueField
